### PR TITLE
Downloader - ensure progress counter <= total

### LINKED ISSUE #40: BUG: download progress bar exceeds max
This an error from a hyrax engine cart, but I think it's coming from fcrepo_wrapper:
```
$ bundle exec rake hydra:server
rake aborted!-4.7.1-jetty-console.jar: |===========================================================================================================  | 99% ( ETA: 00:00:00 )
ProgressBar::InvalidProgressError: You can't set the item's current value to be greater than the total.
/users/dlweber/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/users/dlweber/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
Tasks: TOP => hydra:server
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by dazza-codes**
Fix #40

### CODE REVIEW

**Comment by dazza-codes** [comment]
Pushed up the pattern from solr_wrapper as a separate commit for now, can be squashed if it works.

**Comment by cbeer** [comment]
Shouldn't the `SafeProgressBar` be ported over too? I think that's where the real magic lies..

**Comment by dazza-codes** [comment]
OK, using the `SafeProgressBar` instead of class methods for the procs.  The only difference from the solr-solution is using `total.to_i <= new_progress` because `total` starts out as `nil` and `nil.to_i => 0`.

**Comment by dazza-codes** [comment]
Seems to be working (it's very slow to download today):
```
$ bundle exec fcrepo_wrapper clean
cleaning /tmp/fcrepo-webapp-4.7.2-jetty-console...
$ bundle exec fcrepo_wrapper
Starting Fedora 4.7.2 on port 8080 ...
fcrepo-webapp-4.7.2-jetty-console.jar: |===================         | 75% ( ETA: 00:00:34 )
```

**Pull request merged**
